name: notify
description: Flutter app to demonstrate FCM notifications.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  firebase_core: ^1.2.0
  cloud_firestore: ^2.4.0
  firebase_messaging: ^10.0.0
  flutter_local_notifications: ^8.0.0
  flutter_riverpod: ^0.14.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
